//
// Olympus MakerNote Tag definitions
// Based on https://exiftool.org/TagNames/Olympus.html
//

use super::maker_tag::{MakerTag, MakerNoteVendor};

generate_maker_tags! {
    vendor: Olympus,
    tags: [
    (MakerNoteVersion, 0x0000, "Maker Note Version"),
    (MinoltaCameraSettingsOld, 0x0001, "Minolta Camera Settings Old"),
    (MinoltaCameraSettings, 0x0003, "Minolta Camera Settings"),
    (CompressedImageSize, 0x0040, "Compressed Image Size"),
    (PreviewImageData, 0x0081, "Preview Image Data"),
    (PreviewImageStart, 0x0088, "Preview Image Start"),
    (PreviewImageLength, 0x0089, "Preview Image Length"),
    (ThumbnailImage, 0x0100, "Thumbnail Image"),
    (BodyFirmwareVersion, 0x0104, "Body Firmware Version"),
    (SpecialMode, 0x0200, "Special Mode"),
    (Quality, 0x0201, "Quality"),
    (Macro, 0x0202, "Macro"),
    (BWMode, 0x0203, "BW Mode"),
    (DigitalZoom, 0x0204, "Digital Zoom"),
    (FocalPlaneDiagonal, 0x0205, "Focal Plane Diagonal"),
    (LensDistortionParams, 0x0206, "Lens Distortion Params"),
    (CameraType, 0x0207, "Camera Type"),
    (TextInfo, 0x0208, "Text Info"),
    (CameraID, 0x0209, "Camera ID"),
    (DataDump, 0x0f00, "Data Dump"),
    (ShutterSpeedValue, 0x1000, "Shutter Speed Value"),
    (ISOValue, 0x1001, "ISO Value"),
    (ApertureValue, 0x1002, "Aperture Value"),
    (BrightnessValue, 0x1003, "Brightness Value"),
    (FlashMode, 0x1004, "Flash Mode"),
    (FlashDevice, 0x1005, "Flash Device"),
    (ExposureCompensation, 0x1006, "Exposure Compensation"),
    (SensorTemperature, 0x1007, "Sensor Temperature"),
    (LensTemperature, 0x1008, "Lens Temperature"),
    (LightCondition, 0x1009, "Light Condition"),
    (FocusRange, 0x100a, "Focus Range"),
    (FocusMode, 0x100b, "Focus Mode"),
    (ManualFocusDistance, 0x100c, "Manual Focus Distance"),
    (ZoomStepCount, 0x100d, "Zoom Step Count"),
    (FocusStepCount, 0x100e, "Focus Step Count"),
    (Sharpness, 0x100f, "Sharpness"),
    (FlashChargeLevel, 0x1010, "Flash Charge Level"),
    (ColorMatrix, 0x1011, "Color Matrix"),
    (BlackLevel, 0x1012, "Black Level"),
    (ColorTemperatureBG, 0x1013, "Color Temperature BG"),
    (ColorTemperatureRG, 0x1014, "Color Temperature RG"),
    (WBMode, 0x1015, "WB Mode"),
    (RedBalance, 0x1017, "Red Balance"),
    (BlueBalance, 0x1018, "Blue Balance"),
    (ColorMatrixNumber, 0x1019, "Color Matrix Number"),
    (SerialNumber, 0x101a, "Serial Number"),
    (ExternalFlashAE1_0, 0x101b, "External Flash AE 1.0"),
    (ExternalFlashAE2_0, 0x101c, "External Flash AE 2.0"),
    (InternalFlashAE1_0, 0x101d, "Internal Flash AE 1.0"),
    (InternalFlashAE2_0, 0x101e, "Internal Flash AE 2.0"),
    (ExternalFlashAE1, 0x101f, "External Flash AE 1"),
    (ExternalFlashAE2, 0x1020, "External Flash AE 2"),
    (InternalFlashAE1, 0x1021, "Internal Flash AE 1"),
    (InternalFlashAE2, 0x1022, "Internal Flash AE 2"),
    (FlashExposureComp, 0x1023, "Flash Exposure Comp"),
    (InternalFlashTable, 0x1024, "Internal Flash Table"),
    (ExternalFlashGValue, 0x1025, "External Flash G Value"),
    (ExternalFlashBounce, 0x1026, "External Flash Bounce"),
    (ExternalFlashZoom, 0x1027, "External Flash Zoom"),
    (ExternalFlashMode, 0x1028, "External Flash Mode"),
    (Contrast, 0x1029, "Contrast"),
    (SharpnessFactor, 0x102a, "Sharpness Factor"),
    (ColorControl, 0x102b, "Color Control"),
    (ValidBits, 0x102c, "Valid Bits"),
    (CoringFilter, 0x102d, "Coring Filter"),
    (OlympusImageWidth, 0x102e, "Olympus Image Width"),
    (OlympusImageHeight, 0x102f, "Olympus Image Height"),
    (SceneDetect, 0x1030, "Scene Detect"),
    (SceneArea, 0x1031, "Scene Area"),
    (SceneDetectData, 0x1033, "Scene Detect Data"),
    (CompressionRatio, 0x1034, "Compression Ratio"),
    (PreviewImageValid, 0x1035, "Preview Image Valid"),
    (PreviewImageStart2, 0x1036, "Preview Image Start 2"),
    (PreviewImageLength2, 0x1037, "Preview Image Length 2"),
    (AFResult, 0x1038, "AF Result"),
    (CCDScanMode, 0x1039, "CCD Scan Mode"),
    (NoiseReduction, 0x103a, "Noise Reduction"),
    (InfinityLensStep, 0x103b, "Infinity Lens Step"),
    (NearLensStep, 0x103c, "Near Lens Step"),
    (LightValueCenter, 0x103d, "Light Value Center"),
    (LightValuePeriphery, 0x103e, "Light Value Periphery"),
    (FieldCount, 0x103f, "Field Count"),
    (Equipment, 0x2010, "Equipment"),
    (CameraSettings, 0x2020, "Camera Settings"),
    (RawDevelopment, 0x2030, "Raw Development"),
    (RawDev2, 0x2031, "Raw Dev 2"),
    (ImageProcessing, 0x2040, "Image Processing"),
    (FocusInfo, 0x2050, "Focus Info"),
    (RawInfo, 0x3000, "Raw Info"),
    (MainInfo, 0x4000, "Main Info"),
    ]
}
