//
// Sony MakerNote Tag definitions
// Based on https://exiftool.org/TagNames/Sony.html
//

use crate::make_note::maker_tag::{MakerTag, MakerNoteVendor};

generate_maker_tags! {
    vendor: Sony,
    tags: [
    (CameraInfo, 0x0010, "Camera Info"),
    (FocusInfo, 0x0020, "Focus Info"),
    (Quality, 0x0102, "Quality"),
    (FlashExposureComp, 0x0104, "Flash Exposure Comp"),
    (Teleconverter, 0x0105, "Teleconverter"),
    (WhiteBalanceFineTune, 0x0112, "White Balance Fine Tune"),
    (CameraSettings, 0x0114, "Camera Settings"),
    (WhiteBalance, 0x0115, "White Balance"),
    (ExtraInfo, 0x0116, "Extra Info"),
    (PrintIM, 0x0e00, "Print IM"),
    (MultiBurstMode, 0x1000, "Multi Burst Mode"),
    (MultiBurstImageWidth, 0x1001, "Multi Burst Image Width"),
    (MultiBurstImageHeight, 0x1002, "Multi Burst Image Height"),
    (Panorama, 0x1003, "Panorama"),
    (PreviewImage, 0x2001, "Preview Image"),
    (Rating, 0x2002, "Rating"),
    (Contrast, 0x2004, "Contrast"),
    (Saturation, 0x2005, "Saturation"),
    (Sharpness, 0x2006, "Sharpness"),
    (Brightness, 0x2007, "Brightness"),
    (LongExposureNoiseReduction, 0x2008, "Long Exposure Noise Reduction"),
    (HighISONoiseReduction, 0x2009, "High ISO Noise Reduction"),
    (HDR, 0x200a, "HDR"),
    (MultiFrameNoiseReduction, 0x200b, "Multi Frame Noise Reduction"),
    (PictureEffect, 0x200e, "Picture Effect"),
    (SoftSkinEffect, 0x200f, "Soft Skin Effect"),
    (VignettingCorrection, 0x2011, "Vignetting Correction"),
    (LateralChromaticAberration, 0x2012, "Lateral Chromatic Aberration"),
    (DistortionCorrectionSetting, 0x2013, "Distortion Correction Setting"),
    (WBShiftAB_GM, 0x2014, "WB Shift AB GM"),
    (AutoPortraitFramed, 0x2016, "Auto Portrait Framed"),
    (FlashAction, 0x2017, "Flash Action"),
    (ElectronicFrontCurtainShutter, 0x201a, "Electronic Front Curtain Shutter"),
    (FocusMode, 0x201b, "Focus Mode"),
    (AFAreaModeSetting, 0x201c, "AF Area Mode Setting"),
    (FlexibleSpotPosition, 0x201d, "Flexible Spot Position"),
    (AFPointSelected, 0x201e, "AF Point Selected"),
    (AFPointsUsed, 0x2020, "AF Points Used"),
    (AFTracking, 0x2021, "AF Tracking"),
    (FocalPlaneAFPointsUsed, 0x2022, "Focal Plane AF Points Used"),
    (MultiFrameNREffect, 0x2023, "Multi Frame NR Effect"),
    (WBShiftAB_GM_Precise, 0x2026, "WB Shift AB GM Precise"),
    (FocusLocation, 0x2027, "Focus Location"),
    (VariableLowPassFilter, 0x2028, "Variable Low Pass Filter"),
    (RAWFileType, 0x2029, "RAW File Type"),
    (PrioritySetInAWB, 0x202b, "Priority Set In AWB"),
    (MeteringMode2, 0x202c, "Metering Mode 2"),
    (ExposureStandardAdjustment, 0x202d, "Exposure Standard Adjustment"),
    (Quality2, 0x202e, "Quality 2"),
    (PixelShiftInfo, 0x202f, "Pixel Shift Info"),
    (SerialNumber, 0x2031, "Serial Number"),
    (Shadows, 0x2032, "Shadows"),
    (Highlights, 0x2033, "Highlights"),
    (Fade, 0x2034, "Fade"),
    (SharpnessRange, 0x2035, "Sharpness Range"),
    (Clarity, 0x2036, "Clarity"),
    (FocusFrameSize, 0x2037, "Focus Frame Size"),
    (JPEG_HEIFSwitch, 0x2039, "JPEG-HEIF Switch"),
    (FocusLocation2, 0x204a, "Focus Location 2"),
    (StepCropShooting, 0x205c, "Step Crop Shooting"),
    (ShotInfo, 0x3000, "Shot Info"),
    (AFInfo, 0x940e, "AF Info"),
    (FileFormat, 0xb000, "File Format"),
    (SonyModelID, 0xb001, "Sony Model ID"),
    (CreativeStyle, 0xb020, "Creative Style"),
    (ColorTemperature, 0xb021, "Color Temperature"),
    (ColorCompensationFilter, 0xb022, "Color Compensation Filter"),
    (SceneMode, 0xb023, "Scene Mode"),
    (ZoneMatching, 0xb024, "Zone Matching"),
    (DynamicRangeOptimizer, 0xb025, "Dynamic Range Optimizer"),
    (ImageStabilization, 0xb026, "Image Stabilization"),
    (LensType, 0xb027, "Lens Type"),
    (MinoltaMakerNote, 0xb028, "Minolta Maker Note"),
    (ColorMode, 0xb029, "Color Mode"),
    (LensSpec, 0xb02a, "Lens Spec"),
    (FullImageSize, 0xb02b, "Full Image Size"),
    (PreviewImageSize, 0xb02c, "Preview Image Size"),
    (Macro, 0xb040, "Macro"),
    (ExposureMode, 0xb041, "Exposure Mode"),
    (FocusMode2, 0xb042, "Focus Mode 2"),
    (AFAreaMode, 0xb043, "AF Area Mode"),
    (AFIlluminator, 0xb044, "AF Illuminator"),
    (JPEGQuality, 0xb047, "JPEG Quality"),
    (FlashLevel, 0xb048, "Flash Level"),
    (ReleaseMode, 0xb049, "Release Mode"),
    (SequenceNumber, 0xb04a, "Sequence Number"),
    (AntiBlur, 0xb04b, "Anti-Blur"),
    (FocusMode3, 0xb04e, "Focus Mode 3"),
    (DynamicRangeOptimizer2, 0xb04f, "Dynamic Range Optimizer 2"),
    (HighISONoiseReduction2, 0xb050, "High ISO Noise Reduction 2"),
    (IntelligentAuto, 0xb052, "Intelligent Auto"),
    (WhiteBalance2, 0xb054, "White Balance 2"),
    ]
}
